version: "3.0"

services:
  web:
    image: nginx
    container_name: th_web
    depends_on:
    - app
    ports:
    - "127.0.0.1:8080:80"
    - "127.0.0.1:8443:443"
    volumes:
    - ./docker/letsencrypt:/etc/letsencrypt:Z
    - ./docker/nginx-conf:/etc/nginx/conf.d:Z

  app:
    image: sbaird/tiddlyhost-base:latest
    container_name: th_app
    depends_on:
    - db
    - cache
    volumes:
    - ./rails:/opt/app:Z
    - ./docker/bundle:/opt/bundle:Z
    - ./node_modules:/opt/node_modules:Z
    - ./docker/log:/var/log/app:Z
    - ./docker/dotcache:/home/appuser/.cache:Z
    command: /bin/start-rails.sh
    restart: unless-stopped

    security_opt:
    # Todo: Figure out what syscalls chrome sandbox really needs
    # and use an appropriate policy
    - "seccomp:unconfined"

    build:
      context: .
      dockerfile: docker/Dockerfile.base
      args:
      - USER_ID
      - GROUP_ID

  jobs:
    image: sbaird/tiddlyhost-base:latest
    container_name: th_jobs
    depends_on:
    - db
    - cache
    volumes:
    - ./rails:/opt/app:Z
    - ./docker/bundle:/opt/bundle:Z
    - ./node_modules:/opt/node_modules:Z
    - ./docker/log:/var/log/app:Z
    - ./docker/dotcache:/home/appuser/.cache:Z
    command: /bin/start-delayed-job.sh

    security_opt:
    # Todo: Figure out what syscalls chrome sandbox really needs
    # and use an appropriate policy
    - "seccomp:unconfined"

    # It uses the same image as app so no need for build
    restart: unless-stopped

  cache:
    image: memcached
    container_name: th_cache
    command: memcached -I 8M
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: th_db
    environment:
      # (Only used when the container sets up a brand new db IIUC)
      POSTGRES_PASSWORD: postgres
    # So we can use localhost for the rails db when running
    # on bare metal rather than in the app container
    #ports:
    #- "127.0.0.1:5432:5432"
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z
    restart: unless-stopped
