version: "3.0"

services:
  cache:
    image: memcached
    container_name: th_cache
    command: memcached -I 8M
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: th_db
    environment:
      # (For a brand new fresh deploy you should put the real password here)
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./docker/postgresql-data/data:/var/lib/postgresql/data:Z
    restart: unless-stopped

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.0wiki.ru
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker/dms/mail-data/:/var/mail/
      - ./docker/dms/mail-state/:/var/mail-state/
      - ./docker/dms/mail-logs/:/var/log/mail/
      - ./docker/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  rainloop:
    image: hardware/rainloop
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./docker/rainloop:/rainloop/data
    depends_on:
      - db
      - mailserver

  app:
    image: sbaird/tiddlyhost:latest
    container_name: th_app
    depends_on:
    - db
    - cache
    - mailserver 

    ports:
    - "127.0.0.1:8080:80"

    volumes:
    - ./docker/log:/var/log/app:Z
    - ./docker/secrets/master.key:/opt/app/config/master.key:Z,ro
    - ./docker/secrets/credentials.yml.enc:/opt/app/config/credentials.yml.enc:Z,ro
    - ./docker/config/settings_local.yml:/opt/app/config/settings_local.yml:Z,ro
    - ./docker/config/prerelease.html:/opt/app/tw_content/empties/prerelease.html:Z
    - rails-static:/opt/app/public

    security_opt:
    # Todo: Figure out what syscalls chrome sandbox really needs
    # and use an appropriate policy
    - "seccomp:unconfined"

    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped

  jobs:
    image: sbaird/tiddlyhost:latest
    container_name: th_jobs
    depends_on:
    - db
    - cache
    - mailserver

    volumes:
    - ./docker/log:/var/log/app:Z
    - ./docker/secrets/master.key:/opt/app/config/master.key:Z,ro
    - ./docker/secrets/credentials.yml.enc:/opt/app/config/credentials.yml.enc:Z,ro
    - ./docker/config/settings_local.yml:/opt/app/config/settings_local.yml:Z,ro

    command: /bin/start-delayed-job.sh

    security_opt:
    # Todo: Figure out what syscalls chrome sandbox really needs
    # and use an appropriate policy
    - "seccomp:unconfined"
    restart: unless-stopped

volumes:
  # Share rails public with nginx so it can serve static files directly
  rails-static:
