---
# May be overridden by values in settings_local.yml

defaults:
  github_url: https://github.com/simonbaird/tiddlyhost
  issues_url: https://github.com/simonbaird/tiddlyhost/issues
  docs_url: https://github.com/simonbaird/tiddlyhost/wiki
  faq_url: https://github.com/simonbaird/tiddlyhost/wiki/FAQ
  create_issue_url: https://github.com/simonbaird/tiddlyhost/issues/new
  prod_main_site_url: https://0wiki.ru
  tiddlyhost_account_email: tiddlyhost@0wiki.ru
  devise_mailer_sender: '"0wiki" <tiddlyhost@0wiki.ru>'
  stripe_support_email: '"0wiki" <tiddlyhost@0wiki.ru>'
  support_email: simon.baird@gmail.com
  support_email_name: Simon Baird
  default_user_type_name: basic
  default_empty_name: tw5
  minimum_password_length: 8
  hub_tag_tab_count: 6
  db_host: <%= is_in_container ? "db" : "localhost" %>

  major_version: "1.2"

  #banner_message:
  #  :icon: exclamation-triangle
  #  :html: |
  #    Beware, Tiddlyhost is in the early stages of development and may be
  #    unstable. If you experience problems or have a feature suggestion, please create an
  #    issue in <a href="https://github.com/simonbaird/tiddlyhost/issues">GitHub</a>.

  plan_descriptions:
    :free:
      :features:
      - Create public and private TiddlyWiki & Feather Wiki sites
      - Share your creations with others via the Explore page
    :standard:
      :features:
      - Redirect claimed Tiddlyspot sites to any url
      - View and recover previous versions of your sites with the <b>save history</b> feature
    :premium:
      :features:
      - Custom domain names
      - Externally hosted images and PDFs

  # How many versions of a site to keep
  keep_counts:
    :free: 4
    :standard: 100

development:
  url_defaults:
    :host: 0wiki.ru
    # By "in container" we actually mean running with
    # docker-compose up with the nginx front end
    :protocol: http
    :port: <%= is_in_container ? nil : 3333 %>

  tiddlyspot_host: tiddlyspot.com

test:
  url_defaults:
    :host: example.com
    :protocol: http

  tiddlyspot_host: tiddlyspot-example.com

production:
  url_defaults:
    :host: 0wiki.ru
    #:host: tiddlyhost.local
    :protocol: http

  tiddlyspot_host: tiddlyspot.com
  #tiddlyspot_host: tiddlyspot.local
